Failed mass remove
skroutz/resque pull request #6
Opened 2017-06-28 12:55 UTC by 0xdiba

2017-06-28 13:52 UTC, astathopoulos commented on lib/resque/failure/extra.rb
> +      def remove_older_than(days)
I would add something like:
```
days = [30, days.to_i].min
```
to prevent removing all jobs by mistake.

2017-06-29 12:51 UTC, 0xdiba commented on lib/resque/failure/extra.rb
> +      def remove_older_than(days)
Do we want to restrict usage to such a long interval?
The refreshed UI takes care of some accidents by defaulting to 30 days.

2017-06-29 14:20 UTC, ctrochalakis requested changes

2017-06-29 14:20 UTC, ctrochalakis commented on lib/resque/failure/extra.rb
> +        diff = now - DateTime.parse(job["failed_at"])
What's the unit of that subtraction? Use that unit in the variable name, eg `diff_days`, so it's easier to follow.

2017-06-29 14:20 UTC, ctrochalakis commented on lib/resque/failure/extra.rb
> +      def job_older_than?(job, max_age)
`age` is a better name here.

2017-06-29 14:20 UTC, ctrochalakis commented on lib/resque/failure/extra.rb
> +        $stdout.puts [(diff*24*60).to_i,unit,num].inspect
We can drop that.

2017-06-29 14:20 UTC, ctrochalakis commented on lib/resque/failure/extra.rb
> +        opts.delete(:older_than) if opts[:older_than].empty?
We shouldn't treat `older_than` in a special way, drop all empty/nil value keys.

2017-07-04 09:07 UTC, ctrochalakis commented on lib/resque/failure/extra.rb
> +        unit = age[-1,1]
`age[-1]`

2017-07-04 09:08 UTC, ctrochalakis approved these changes

2017-07-04 11:33 UTC, merged